Lesson 2: basic components
RomanSerikov/react-shop pull request #1
Opened 2018-07-21 00:24 UTC by RomanSerikov

- Создайте модуль constants/Products, экспортирующий массив объектов с описанием товаров ({ id, title, price, imageUrl }). Это временно будет списком товаров.
- Реализовать компонент Image для вывода картинки. В качестве свойств передавать компоненту src (ссылка на картинку), width, height (высота и ширина) и alt (альтернативный текст к картинке). Вывести тестовый элемент компонента на html-странице
- Реализовать компонент TextBox, получающий в качестве дочернего элемента строку с некоторым текстом и возвращающий её в блоке span. Вывести тестовый элемент компонента на html-странице
- Реализовать компонент Price
- Собрать из реализованных ранее компонентов TextBox, Price и Image компонент ProductCard для короткого представления продукта в магазине; Вывести три тестовых элемента продукта на html-странице
- Создать компонент Catalog для вывода списка продуктов в магазине. Передать ему с помощью свойств массив объектов c описанием продукта (ссылка на картинку и текст). Компонент должен представить продукты в виде списка из элементов Product. Вывести результат на html-странице

Усложненное задание: 

- Создать контейнерный компонент CatalogPage, который будет передавать массив записей о продуктах компоненту Catalog.

2018-07-21 08:58 UTC, erisnuts requested changes

2018-07-21 08:58 UTC, erisnuts commented on src/Catalog.js
> +      <ul>
если используется тег ul, внутри должны быть теги li

2018-07-21 08:58 UTC, erisnuts commented on src/Catalog.js
> +        alt='I am placeholder'
в качестве alt стоит передать что-то характеризующее картинку, например, title

2018-07-21 08:58 UTC, erisnuts commented on src/Catalog.js
> +        key={ product.id.toString() }
здесь лучше использовать интерполяцию строк \`${product.id}`

2018-07-21 08:58 UTC, erisnuts commented on src/Catalog.js
> +    const products = this.props.products;
здесь было бы хорошо деструктурировать объект product. 
`const { id, imageUrl, title, price } = this.props.product;`
чтобы избавить от повторения.

2018-07-21 08:58 UTC, erisnuts commented on src/Catalog.js
> +        {listItems}
переменную listItems можно назвать redundant - она используется один раз и от нее можно избавиться без потери читабельности. получится
`<div>{products.map(...)}</div>`.

2018-07-21 08:58 UTC, erisnuts commented on src/CatalogPage.js
> +  constructor() {
надо писать: `constructor(props) {
super(props);
}`
документация: https://reactjs.org/docs/react-component.html#constructor

2018-07-21 08:58 UTC, erisnuts commented on src/CatalogPage.js
> +    this.setState({ products: Products });
изменение состояния в методе componentDidMount повлечет за собой лишний re-render. в этом методе обычно выполняются функции, для которых, например, нужен непосредственно браузер: обращения к document или window.

2018-07-21 08:58 UTC, erisnuts commented on src/CatalogPage.js
> +    return <Catalog products={this.state.products} />;
в данном случае будет достаточно написать `products={this.props.products}`. управлять списком продуктов (фильтровать, например) будет не компонент CatalogPage, а компонент Catalog

2018-07-21 08:58 UTC, erisnuts commented on src/CatalogPage.js
> +    this.state = { products: [] }
этот компонент можно сделать stateless

2018-07-21 08:58 UTC, erisnuts commented on src/CatalogPage.js
> +import { Products } from './constants/products';
принято с большой буквы писать только имена компонентов.

2018-07-21 08:58 UTC, erisnuts commented on src/CatalogPage.js
> +    return <Catalog products={this.state.products} />;
и даже в компоненте Catalog для фильтрации не надо будет копировать список продуктов в состояние. достаточно будет хранить только значение фильтра.

2018-07-21 08:58 UTC, erisnuts commented on src/Image.js
> +    <img src={ src } width={ width } height={ height } alt={ alt } />
`src={ src }` -> `src={src}` - пробелы не нужны.

2018-07-21 13:29 UTC, erisnuts requested changes

2018-07-21 13:29 UTC, erisnuts commented on src/CatalogPage.js
> +    this.state = { products: [] }
{ products: Products } можно сделать в конструкторе

2018-07-21 13:29 UTC, erisnuts commented on index.js
> +        <Image src='https://placeimg.com/300/200/tech' width='300' height='200' alt='I am placeholder' />
если это отладочный вызов компонентов, его следует убрать.

2018-07-21 13:55 UTC, RomanSerikov commented on src/Catalog.js
> +    const products = this.props.products;
не совсем понимаю как правильно деструктурировать и потом в map это передать

2018-07-21 14:03 UTC, RomanSerikov commented on index.js
> +        <Image src='https://placeimg.com/300/200/tech' width='300' height='200' alt='I am placeholder' />
В задании было: "Реализовать компонент Image для вывода картинки. В качестве свойств передавать компоненту src (ссылка на картинку), width, height (высота и ширина) и alt (альтернативный текст к картинке). Вывести тестовый элемент компонента на html-странице"

2018-07-21 14:03 UTC, RomanSerikov commented on index.js
> +        <Image src='https://placeimg.com/300/200/tech' width='300' height='200' alt='I am placeholder' />
Если это лишнее, могу убрать

2018-07-23 08:26 UTC, erisnuts requested changes

2018-07-23 08:26 UTC, erisnuts commented on src/Catalog.js
> +    const products = this.props.products;
в `map` можно передать `this.props.products`

2018-07-23 08:26 UTC, erisnuts commented on index.js
> +        <Image src='https://placeimg.com/300/200/tech' width='300' height='200' alt='I am placeholder' />
выполнено правильно, по заданию, но в конечном счете - лишнее, потому что вскоре будем выводить на страницу только данные полученные с API.

2018-07-23 08:26 UTC, erisnuts commented on src/Catalog.js
> +        {redundant}
redundant переводится как "лишний, ненужный". я имела в виду, что можно (лучше) не вводить эту промежуточную переменную. если будет использоваться линтер, то в этом и подобных случаях он будет показывать замечание вида "this variable is redundant".
(но это не критично и ошибкой не является, если этой переменной быть, то достаточно будет ее переименовать обратно в listItems).

2018-07-26 07:53 UTC, index01d approved these changes

2018-07-26 07:53 UTC, index01d commented on src/ProductCard.js
> +    const { imageUrl, title, price } = this.props.product;
можно было создать объект `image: { src, width, height, alt }`

2018-07-26 07:53 UTC, index01d commented on src/ProductCard.js
> +        <Image src={imageUrl} width='300' height='200' alt={title} />
тогда здесь бы получилось просто `<Image {...image} />`

2018-07-26 19:42 UTC, merged